version: '3.7'
networks:
  mojaloop-net:
    name: mojaloop-net

services:
  iso-core-connector:
    networks:
      - mojaloop-net
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "3003:3003"

  mockserver:
    networks:
      - mojaloop-net
    image: jamesdbloom/mockserver
    container_name: iso-mockserver
    ports:
      - "1080:1080"

  redis:
    networks:
        - mojaloop-net
    image: "redis:6.2.6-alpine3.15"
    container_name: iso-redis
    ports:
      - "6379:6379"
