openapi: 3.0.1
info:
  title: ISO 20022 Core Connector
  description: ISO 20022 Core Connector for Mojaloop
  version: 0.0.1
  license:
    name: Apache-2.0

paths:
  /health:
    get:
      summary: Health check endpoint
      description: This endpoint checks the health of the service.
      tags:
        - Health
      responses:
        200:
          description: Returns a success response code if the service is healthy.
  
  /inbound/parties/:idType/:idValue:
    get:
      summary: GET parties
      description: GET parties
      tags:
        - PartiesByTypeAndID
      responses:
        200:
          description: OK
        404:
          description: Not Found - The resource specified in the URI was not found.
          content:
            application/json:
              schema:
                title: NotFoundError
                type: object
                properties:
                  statusCode: 
                    description: Mojaloop error code
                required:
                  - statusCode

  /inbound/quoterequests:
    post:
      summary: Quotes request
      description: Quotes request
      tags:
        - postQuotes
      requestBody:
        content:
          application/json:
            schema:
              title: QuotesPostRequest
              type: object
              properties:
                from:
                  title: Payer party
                  description: Information about the Payer
                  type: object
                  properties:
                    idType:
                      description: Payer's identity type
                    idValue:
                      description: Payer's identifier
                    idSubValue:
                      description: Payer's sub-id
                    fspId:
                      description: Payer's FSP ID
                    extensionList:
                      description: Extension list
                    displayName:
                      description: Payer's display name
                    dateOfBirth:
                      description: Payer's birth date
                    firstName:
                      description: Payer's first name
                    middleName:
                      description: Payer's middle name
                    lastName:
                      description: Payer's last name
                to:
                  title: Payee party
                  description: Information about the Payee
                  type: object
                  properties:
                    idType:
                      description: Payee's identity type
                    idValue:
                      description: Payee's identifier
                    idSubValue:
                      description: Payee's sub-id
                    fspId:
                      description: Payee's FSP ID
                    extensionList:
                      description: Extension list
                    displayName:
                      description: Payee's display name
                    dateOfBirth:
                      description: Payee's birth date
                    firstName:
                      description: Payee's first name
                    middleName:
                      description: Payee's middle name
                    lastName:
                      description: Payee's last name
                quoteId:
                  description: Quote ID
                transactionId: 
                  description: Common ID (decided by the Payer FSP) between the FSPs for the future transaction object.
                amountType:
                  description: Amount type - SEND or RECEIVE
                amount:
                  description: Quote amount.
                currency:
                  description: Quote currency.
                transactionType:
                  description: Transaction scenario
                initiator:
                  description: Initiator
                initiatorType:
                  description: Initiator type
                feeAmount:
                  description: Fee amount
                feeCurrency:
                  description: Fee currency
                geoCode:
                  description: Geo code
                note:
                  description: Note
                expiration:
                  description: Quote expiration
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                title: Quote response
                type: object
                properties:
                  quoteId:
                    description: Quote ID
                  transactionId:
                    description: Transaction ID
                  transferAmount:
                    description: Transfer amount
                  payeeReceiveAmount:
                    description: Payee receive amount
                  transferAmountCurrency:
                    description: Transfer amount currency
                  payeeReceiveAmountCurrency:
                    description: Payee receive amount currency
                  expiration:
                    description: Transfer expiration
        500:
          description: Quote error
          content:
            application/json:
              schema:
                title: Quote error
                type: object
                properties:
                  statusCode: 
                    description: Mojaloop error code
                required:
                  - statusCode 
  
  /inbound/transfers:
    post:
      summary: Transfer request
      description: Transfer request
      tags:
        - postTransfer
      requestBody:
        content:
          application/json:
            schema:
              title: TransfersPostRequest
              type: object
              oneOf:
                - properties:
                    transferId:
                      description: Transfer ID
                    quote:
                      description: Quote response
                      type: object
                      properties:
                        quoteId:
                          description: Quote ID
                        transactionId:
                          description: Transaction ID
                        transferAmount:
                          description: Transfer amount
                        payeeReceiveAmount:
                          description: Payee receive amount
                        payeeReceiveAmountCurrency:
                          description: Payee receive amount currency
                        expiration:
                          description: Quote expiration
                    from:
                      title: Payer party
                      description: Information about the Payer
                      type: object
                      properties:
                        idType:
                          description: Payer's identity type
                        idValue:
                          description: Payer's identifier
                        idSubValue:
                          description: Payer's sub-id
                        fspId:
                          description: Payer's FSP ID
                        extensionList:
                          description: Extension list
                        displayName:
                          description: Payer's display name
                        dateOfBirth:
                          description: Payer's birth date
                        firstName:
                          description: Payer's first name
                        middleName:
                          description: Payer's middle name
                        lastName:
                          description: Payer's last name
                    to:
                      title: Payee party
                      description: Information about the Payee
                      type: object
                      properties:
                        idType:
                          description: Payee's identity type
                        idValue:
                          description: Payee's identifier
                        idSubValue:
                          description: Payee's sub-id
                        fspId:
                          description: Payee's FSP ID
                        extensionList:
                          description: Extension list
                        displayName:
                          description: Payee's display name
                        dateOfBirth:
                          description: Payee's birth date
                        firstName:
                          description: Payee's first name
                        middleName:
                          description: Payee's middle name
                        lastName:
                          description: Payee's last name
                    amount:
                      description: Amount
                    amountType:
                      description: Amount type
                    currency:
                      description: Currency
                    transactionType:
                      description: Transactioon type
                    note:
                      description: Note
                - properties:
                    transferId:
                      description: Transfer ID
                    currency:
                      description: Currency
                    amount:
                      description: Amount
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                title: Transfer response
                type: object
                properties:
                  homeTransactionId:
                    description: Backend transaction identifier
        500:
          description: Tranfer error
          content:
            application/json:
              schema:
                title: Tranfer error
                type: object
                properties:
                  statusCode: 
                    description: Mojaloop error code
                required:
                  - statusCode 

  /outbound/iso20022:
    post:
      summary: POST ISO 20022 message
      description: POST ISO 20022 message
      tags:
        - postISO20022
      requestBody:
        content:
          application/xml:
            schema:
              oneOf:
                - $ref: '#/components/schemas/PAIN.001'
                - $ref: '#/components/schemas/PAIN.002'
                - $ref: '#/components/schemas/PAIN.008'
                - $ref: '#/components/schemas/PAIN.013'
      responses:
        200:
          description: OK


components:
  schemas:
    PAIN.001:
      type: object
      description: ISO 20022 PAIN.001 message
      xml:
        name: 'Document'
        namespace: 'http://www.w3.org/2001/XMLSchema-instance'
      properties:
        CstmrCdtTrfInitn:
          type: object
          properties:
            GrpHdr:
              type: object
              properties:
                MsgId:
                  type: string
                CreDtTm:
                  type: string
                NbOfTxs:
                  type: integer
                InitgPty:
                  type: object
                  properties:
                    Nm:
                      type: string
                    Id:
                      type: object
                      properties:
                        OrgId:
                          type: object
                          properties:
                            AnyBIC:
                              type: string
                PmtInf:
                  type: object
                  properties:
                    PmtInfId:
                      type: string
                    PmtMtd:
                      type: string
                    ReqdExctnDt:
                      type: object
                      properties:
                        Dt:
                          type: string
                    Dbtr:
                      type: object
                      properties:
                        CtctDtls:
                          type: object
                          properties:
                            MobNb:
                              type: string
                    DbtrAcct:
                      type: object
                      properties:
                        Id:
                          type: object
                          properties:
                            Othr:
                              type: object
                              properties:
                                Id:
                                  type: string
                    DbtrAgt:
                      type: object
                      properties:
                        FinInstnId:
                          type: object
                          properties:
                            BICFI:
                              type: string
                            Nm:
                              type: string
                    ChrgBr:
                      type: string
                    CdtTrfTxInf:
                      type: object
                      properties:
                        PmtId:
                          type: object
                          properties:
                            EndToEndId:
                              type: string
                        Amt:
                          type: object
                          properties:
                            InstdAmt:
                              type: string
                              # TODO: Nee to represent the currency attribute ("Ccy") of InstdAmt
                        Cdtr:
                          type: object
                          properties:
                            CtctDtls:
                              type: object
                              properties:
                                MobNb:
                                  type: string
                        

                    

